services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java17
    volumes:
    - ./modpacks:/modpacks:ro
    - ./mc-data:/data
    environment:
      UID: 1000
      GID: 1000
      TZ: /etc/localtime:/etc/localtime:ro
      EULA: true
      MOTD: "CHANGEME"
      MAX_PLAYERS: 5
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      ALLOW_FLIGHT: true
      ENABLE_WHITELIST: true
      WHITELIST: "remag29"
      OVERRIDE_WHITELIST: true
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: "CHANGEME" # Example: "/modpacks/Mer_Bleue_SERVER_1.1.0.mrpack"
      MEMORY: 10G
      VERSION: "1.20.1"
    ports:
      - "25565:25565" # Server
      # - "24454:24454/udp" # Expose port for mod Voice Chat
    restart: unless-stopped
